### ISSUE TITLE
Versioning issues with tensorflow

### ISSUE THREAD

**Issue by TIM-ysh** [LWT3437/LANet#1]
WARNING:tensorflow:From j:\TIM\HDR\ITM_method\LANET\LANet-main\LANet-main\LANet\src\model.py:161: start_queue_runners (from tensorflow.python.training.queue_runner_impl) is deprecated and will be removed in a future version.

Because this function was deprecated it caused the program to hang and not run. Is there any way to fix this? If you can answer this, thank you for your answer.

**Comment by LWT3437** [comment]
@godnessTIM  Thank you for taking an interest in our work. The warning wouldn’t cause running error, it should be caused by other reasons. 

In addition, if my memory is correct, the 'start_queue_runners' function will only run in training mode. Are you trying to use training mode? If so, I suggest not to do this. 

This code was written a long time ago and is now outdated and difficult to maintain, so we didn't provide a guide on how to retrain. If you intend to train your own model, we recommend re-implementing it with a more advanced framework.

**Comment by TIM-ysh** [comment]
Thank you for your answer.
